package com.example.recipeapp.dao

data class Maps(
    val staples: Map<String, Int> = mapOf(
        "milk" to 1,
        "eggs" to 2,
        "flour" to 3,
        "rice" to 4,
        "potatoes" to 5,
        "butter" to 6,
        "pasta" to 7,
        "onions" to 8,
        "garlic" to 9,
        "kumara" to 10,
        "corn" to 11,
        "chicken" to 12,
        "bacon" to 13
    ),/**
    val countries: Map<String, String> = mapOf(
        "america" to "🇺🇸",
        "australia" to "🇦🇺",
        "austria" to "🇦🇹",
        "belgium" to "🇧🇪",
        "brazil" to "🇧🇷",
        "canada" to "🇨🇦",
        "china" to "🇨🇳",
        "croatia" to "🇭🇷",
        "czech" to "🇨🇿",
        "denmark" to "🇩🇰",
        "egypt" to "🇪🇬",
        "finland" to "🇫🇮",
        "france" to "🇫🇷",
        "germany" to "🇩🇪",
        "greece" to "🇬🇷",
        "hungary" to "🇭🇺",
        "india" to "🇮🇳",
        "indonesia" to "🇮🇩",
        "ireland" to "🇮🇪",
        "italy" to "🇮🇹",
        "japan" to "🇯🇵",
        "malaysia" to "🇲🇾",
        "mexico" to "🇲🇽",
        "netherlands" to "🇳🇱",
        "new zealand" to "🇳🇿",
        "norway" to "🇳🇴",
        "philippines" to "🇵🇭",
        "poland" to "🇵🇱",
        "portugal" to "🇵🇹",
        "romania" to "🇷🇴",
        "russia" to "🇷🇺",
        "singapore" to "🇸🇬",
        "south africa" to "🇿🇦",
        "south korea" to "🇰🇷",
        "spain" to "🇪🇸",
        "sweden" to "🇸🇪",
        "switzerland" to "🇨🇭",
        "thailand" to "🇹🇭",
        "turkey" to "🇹🇷",
        "uk" to "🇬🇧",
        "ukraine" to "🇺🇦",
        "vietnam" to "🇻🇳"
    ),*/
    val NORTH_AMERICA: Int = 1,
    val SOUTH_AMERICA: Int = 2,
    val AFRICA: Int = 3,
    val EUROPE: Int = 4,
    val ASIA: Int = 5,
    val OCEANIA: Int = 6,
)
